name: Run Docker-Based Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # force all pulls/runs to use amd64 images
      DOCKER_DEFAULT_PLATFORM: linux/amd64
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Pull required Docker images
        run: |
          docker pull node:lts-slim
          docker pull mcr.microsoft.com/playwright:v1.52.0-noble
          docker pull alfonsograziano/node-chartjs-canvas:latest

      - name: Run tests
        run: npm test
