name: Run Docker-Based Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci
      - name: Pull required Docker images
        run: |
          docker pull --platform=linux/amd64 node:lts-slim
          docker pull --platform=linux/amd64 mcr.microsoft.com/playwright:v1.52.0-noble
          
        # Not adding tbis one as has been built only for arm64 for now
        # docker pull --platform=linux/amd64 alfonsograziano/node-chartjs-canvas:latest

      - name: Run tests
        run: npm test
