name: Run Docker‑Based Tests

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Ensure Docker is running (Windows)
        if: runner.os == 'Windows'
        run: Start-Service Docker
        shell: pwsh

      - name: Pull required Docker images (Linux)
        if: runner.os == 'Linux'
        run: |
          docker pull --platform=linux/amd64 node:lts-slim
          docker pull --platform=linux/amd64 mcr.microsoft.com/playwright:v1.52.0-noble
          docker pull --platform=linux/amd64 alfonsograziano/node-code-sandbox-mcp:latest
        shell: bash

      - name: Pull required Docker images (Windows)
        if: runner.os == 'Windows'
        run: |
          docker pull node:lts-slim
          docker pull mcr.microsoft.com/playwright:v1.52.0-noble
          docker pull alfonsograziano/node-code-sandbox-mcp:latest
        shell: pwsh

      - name: Run tests
        run: npm test
        shell: bash
